name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 203.109.124.70
          username: evoluzn
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/evoluzn/Anjali/Testing_CI_CD/Hotel_mang_CICD
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl restart myflaskapp
